version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.0
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra-cluster"
    volumes:
      - ./cassandra/data:/var/lib/cassandra
