version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.0
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra-cluster"
    volumes:
      - ./cassandra/data:/var/lib/cassandra

  hbase:
    image: harisekhon/hbase:latest
    command: master
    volumes:
      - ./hbase/data:/var/lib/hbase

  db2:
    image: ibmcom/db2
    restart: always
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1-pwd
      DBNAME: db2inst1
      PERSISTENT_HOME: "false" # (default: true) Specify to false if you are running Docker for Windows.
      ARCHIVE_LOGS: "false" # (default: true) Specify false to not configure log archiving (reduces start up time)
      TEXT_SEARCH: "false" # (default: false) Specify true to enable and configure text search
    volumes:
      - ./db2/data:/database
