CREATE USER developer WITH PASSWORD 'PASSWORD';
GRANT CONNECT ON DATABASE TO developer;
GRANT SELECT, INSERT, UPDATE ON books, users, rent TO developer;

CREATE USER client WITH PASSWORD 'PASSWORD';
GRANT CONNECT ON DATABASE TO client;
GRANT SELECT ON books, users, rent TO client;
