version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    restart: always
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_PASSWORD: oracle
    volumes:
      - ./data:/opt/oracle/oradata
