version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:4.0
    restart: always
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra-cluster"
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
    volumes:
      - ./etc/cassandra:/etc/cassandra
      - ./data:/var/lib/cassandra
