CREATE ROLE developer WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT SELECT, INSERT, UPDATE ON books, users, rent TO developer;

CREATE ROLE client WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT SELECT ON books, rent TO client;
